export const componentInfoMap = {
    "Browser": "Sound Browser",
    "Playlist": "Playlist",
    "Transport": "Transport",
    "StripMenu": "Strip Menu",
    "AnalogSynth": "View Analog Synth",
    "Modulator": "View Modulator",
    "New": "Create a new project",
    "Save As": "Save project As",
    "Save": "Save current project",
    "Load": "Load an existing project",
    "Settings": "Change settings",
    "Quit": "Quit the application",
    "ChannelRack": "Add / Delete channels",
    "ChRackUpload": "Load a sample",
    "ChRackPiano": "Add pianoRoll",
    "ChRackDelete": "Delete a channel",
    "ChRackRename": "Rename a channel",
    "ChRackCreate": "Confirm channel to add",
    "ChRackAdd": "Add a new channel",
    "Play Song": "Play in song mode", 
    "Play Pattern": "Play current pattern",
    "Stop Song": "Stop the song",
    "Stop Pattern": "Stop current pattern", 
    "Record": "Record sequence", 
    "Replay": "Replay recorded sequence", 
    "Clear": "Clear recorded sequence", 
    "BPM": "Adjust BPM",
    "LoopMode": "Toggle Loop Mode",
    "SongMode": "Toggle Song Mode",
    "PatternMode": "Toggle Pattern Mode",
    "ChReset": "Set default channels"
};
